
spring:
  application:
    name: API Forum
# datasource
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:alura-forum
    username: sa
    password:
# jpa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
# h2
  h2:
    console:
      enabled: true
      path: /h2-console